apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-02-20T11:55:49Z"
  name: carts-canary
  resourceVersion: "284084"
  selfLink: /api/v1/namespaces/sockshop-staging/services/carts
  uid: f00e651a-53d7-11ea-a0de-42010a8000f8
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: carts
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
